name: CI
on:
  pull_request: {}
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check out code
        uses: actions/checkout@v2
      - name: caching deps
        run: deno cache --lock=deps-lock.json deps.ts
      - name: compiling executable for x86_64-unknown-linux-gnu
        run: deno compile --allow-read --allow-run --allow-write --allow-env --target=x86_64-unknown-linux-gnu --output=/tmp/render-linux-x86_64 ./entry-point.ts
      - name: compiling executable for x86_64-apple-darwin
        run: deno compile --allow-read --allow-run --allow-write --allow-env --target=x86_64-apple-darwin --output=/tmp/render-macos-x86_64 ./entry-point.ts 
      - name: compiling executable for aarch64-apple-darwin
        run: deno compile --allow-read --allow-run --allow-write --allow-env --target=aarch64-apple-darwin --output=/tmp/render-macos-aarch64 ./entry-point.ts
      - name: compiling executable for x86_64-pc-windows-msvc
        run: deno compile --allow-read --allow-run --allow-write --allow-env --target=x86_64-pc-windows-msvc --output=/tmp/render-windows-x86_64 ./entry-point.ts
      - name: setting chmod
        run: chmod +x /tmp/render-*
      - name: uploading artifacts (all)
        uses: actions/upload-artifact@v2
        with:
          name: render-binaries
          path: /tmp/render-*

  make-release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: mkdir -p /tmp/artifacts
      - uses: actions/download-artifact@v3
        with:
          name: render-binaries
          path: /tmp/artifacts
      - name: Do GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            /tmp/artifacts/*
            LICENSE
            README.md
