name: CI
on:
  pull_request: {}
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check out code (full depth for tags)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: caching deps
        run: make deps
      # this version will be a bare tag if this commit is the most recent
      # tag, or will be of the form `v0.1.0-N-aabbccdd`, where the `N` is
      # the number of commits since the last tag and `aabbccdd` is the git
      # hash of the current commit.
      - name: outputting version
        run: make write-raw-version
      - name: compiling executable for x86_64-unknown-linux-gnu
        run: make build-linux-x86_64
      - name: compiling executable for x86_64-apple-darwin
        run: make build-macos-x86_64
      - name: compiling executable for aarch64-apple-darwin
        run: make build-macos-aarch64
      - name: compiling executable for x86_64-pc-windows-msvc
        run: make build-windows-x86_64
      - name: setting chmod
        run: chmod +x /tmp/render-*
      - name: test-running linux artifact just to be sure...
        run: /tmp/render-linux-x86_64 version
      - name: uploading artifacts (all)
        uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: render-binaries
          path: /tmp/render-*

  make-release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: mkdir -p /tmp/artifacts
      - uses: actions/download-artifact@v3
        with:
          name: render-binaries
          path: /tmp/artifacts
      - name: Do GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            /tmp/artifacts/*
            LICENSE
            README.md
